"""Dashboard card metadata registry.

This registry is intentionally metadata-only for now. It does not drive
rendering order or visibility in app.py yet.
"""

DASHBOARD_CARDS = [
    {
        "card_id": "K00",
        "title": "Market Pulse",
        "group": "market",
        "default_order": 0,
        "mobile_priority": 1,
        "enabled": True,
    },
    {
        "card_id": "K01",
        "title": "Guncel Deger",
        "group": "portfolio_overview",
        "default_order": 1,
        "mobile_priority": 1,
        "enabled": True,
    },
    {
        "card_id": "K02",
        "title": "Toplam K/Z",
        "group": "portfolio_overview",
        "default_order": 2,
        "mobile_priority": 1,
        "enabled": True,
    },
    {
        "card_id": "K03",
        "title": "Fon Sayisi",
        "group": "portfolio_overview",
        "default_order": 3,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K04",
        "title": "Pozitif Fon",
        "group": "portfolio_overview",
        "default_order": 4,
        "mobile_priority": 3,
        "enabled": True,
    },
    {
        "card_id": "K05",
        "title": "Gunluk Getiri",
        "group": "portfolio_overview",
        "default_order": 5,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K06",
        "title": "Gunluk K/Z",
        "group": "portfolio_overview",
        "default_order": 6,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K07",
        "title": "Risk Intelligence Center",
        "group": "risk",
        "default_order": 7,
        "mobile_priority": 1,
        "enabled": True,
    },
    {
        "card_id": "K07A",
        "title": "Theme Concentration Engine",
        "group": "risk",
        "default_order": 8,
        "mobile_priority": 3,
        "enabled": True,
    },
    {
        "card_id": "K08",
        "title": "AI Portfolio Awareness Feed",
        "group": "awareness",
        "default_order": 9,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K08A",
        "title": "Liquidity / Exit Engine",
        "group": "awareness",
        "default_order": 10,
        "mobile_priority": 3,
        "enabled": True,
    },
    {
        "card_id": "K09",
        "title": "Portfoy Dagilimi",
        "group": "analytics",
        "default_order": 11,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K10",
        "title": "Fon Bazli K/Z",
        "group": "analytics",
        "default_order": 12,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K10B",
        "title": "Performance Attribution Engine",
        "group": "analytics",
        "default_order": 13,
        "mobile_priority": 3,
        "enabled": True,
    },
    {
        "card_id": "K11",
        "title": "Exposure Engine",
        "group": "exposure",
        "default_order": 14,
        "mobile_priority": 1,
        "enabled": True,
    },
    {
        "card_id": "K11A",
        "title": "Historical Snapshot Trend",
        "group": "snapshot",
        "default_order": 15,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K12",
        "title": "Fon Tablosu",
        "group": "portfolio_table",
        "default_order": 16,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K12A",
        "title": "Quick Position Update",
        "group": "portfolio_table",
        "default_order": 17,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K12B",
        "title": "Selected Position Intelligence",
        "group": "portfolio_table",
        "default_order": 18,
        "mobile_priority": 3,
        "enabled": True,
    },
    {
        "card_id": "K13",
        "title": "Portfolio Editor",
        "group": "editor",
        "default_order": 19,
        "mobile_priority": 3,
        "enabled": True,
    },
    {
        "card_id": "K13A",
        "title": "Metadata Editor",
        "group": "editor",
        "default_order": 20,
        "mobile_priority": 3,
        "enabled": True,
    },
    {
        "card_id": "K14",
        "title": "Portfolio Health Monitor",
        "group": "health",
        "default_order": 21,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K15",
        "title": "Data Quality Monitor",
        "group": "quality",
        "default_order": 22,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K16",
        "title": "Macro Scenario Simulator",
        "group": "scenario",
        "default_order": 23,
        "mobile_priority": 2,
        "enabled": True,
    },
    {
        "card_id": "K16A",
        "title": "Scenario Driver Breakdown",
        "group": "scenario",
        "default_order": 24,
        "mobile_priority": 3,
        "enabled": True,
    },
    {
        "card_id": "K17",
        "title": "Portfolio Change Tracker",
        "group": "snapshot",
        "default_order": 25,
        "mobile_priority": 3,
        "enabled": True,
    },
]


DASHBOARD_CARD_BY_ID = {
    card["card_id"]: card
    for card in DASHBOARD_CARDS
}
